api_hash: fbed0648cea2c92293bd24fb1950cf37
api_id: 24795901
chat:
- chat_id: -1001932120359
  last_read_message_id: 0
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
file_name_prefix:
- chat_title
- message_id
- file_name
file_name_prefix_split: ' - '
file_path_prefix:
- chat_title
- media_datetime
media_types:
- photo
save_path: F:\Downloads\JDown
web_host: 127.0.0.1
web_port: 5000
disable_syslog: []
language: EN
